spring:
  application:
    name: order
  rabbitmq:
    host: 47.105.124.62
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_shell?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhangqiyang0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
mybatis:
  type-aliases-package: com.imooc.order.dao
  mapper-locations: mappers/*.xml
env: dev3
