spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhangqiyang0
    url: jdbc:mysql://localhost:3306/springcloud_shell?useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.imooc.product.dao.ProductDao
env: dev
